auth:
  encrypt:
    private-key: MIICWwIBAAKBgQCm17HXf6Bsmi+Qc3EK2t/io/hdp0SfJkzDFyhftnI4Bb+mq1OCokpcu0tDCNwE9LrIvKmnFsWKGIGmwtGDdqe442A/sQ14qEvpDH1tsZgSWZigyXWyPUpLNi4afwJAegu4apPSPn5ZmL8bs311aVpTRAzht17uk6YmLJDudaYn1wIDAQABAoGAZ/gyEyCtUAAlc9b8ss8ChbG4rGP4F1U+sLRVrI99TfwHGk3ZlKadwHvWwsdalJwNadpnvoAqSYxL/yeYeFwQ19g/Mdu406cUqOQSKXko/z+O61INOIgCopq+Kf1IHlDxlKn5sl4oGmysnQx/nv73/QyWlxGBPdHSyQgkWAyqt4ECQQD6esJTof/KSIXV0ntByEQ43VJzXgZPPosxFEAFUGfGi0V3VWBXhu82paZZZeU6YanFyiu3w/4BQEg0T0Jsi8qJAkEAqoULQy0X4jk+2jpVGuXEWIGrTXa75Nli3QdepBsVEkeynU1pYM7X0u+gBR0oY2GYKfDZJp4abOJdLJOCtUpHXwJAWgW4xdoZVphOEZU+W1wguNdChNgsKFrwJ8mBYOePBJqVctgqcgq6+sb6THMEucDUBZQttjQonEaALNy3oM91EQJAQSa0NuZzyau1qAvBmJVRf7+Lg/1prPaiH3FBZ9IxKtraE+AP8z0UmTOVIF8Tn2UajmvHjEm8Lv4OO4ng1wOaYQJAPDiuJxVpwa7/ZBP1JW3a4/IvqAfamjgrD5HFQFHshknFwjRnTzJt+aznH9jWASCHRp5OFrUgujmYVRUtBeapyg==

# sa-token配置
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: token
  # token 有效期（单位：秒），-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: 3600
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: tik
  # 是否输出操作日志
  is-log: true